name: Autoformat with Black

on:
  pull_request:
    branches:
      - main

jobs:
  autoformat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: psf/black@stable

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Autoformat code with Black"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
